var dir_2534fabef37d53a9be799c6b35cbe4e0 =
[
    [ "average.h", "backend_2average_8h.html", null ],
    [ "cusp_precon_blas.h", "cusp__precon__blas_8h_source.html", null ],
    [ "cusp_thrust_backend.h", "cusp__thrust__backend_8h_source.html", null ],
    [ "cusp_vector_blas.h", "cusp__vector__blas_8h_source.html", null ],
    [ "derivatives.h", "derivatives_8h.html", "derivatives_8h" ],
    [ "dlt.h", "dlt_8h_source.html", null ],
    [ "dx.h", "dx_8h.html", "dx_8h" ],
    [ "dxmatrix_traits.h", "dxmatrix__traits_8h_source.html", null ],
    [ "functions.h", "functions_8h.html", "functions_8h" ],
    [ "grid.h", "grid_8h.html", null ],
    [ "matrix_categories.h", "matrix__categories_8h_source.html", null ],
    [ "matrix_traits.h", "matrix__traits_8h_source.html", null ],
    [ "matrix_traits_thrust.h", "matrix__traits__thrust_8h_source.html", null ],
    [ "mpi_collective.h", "mpi__collective_8h_source.html", null ],
    [ "mpi_derivatives.h", "mpi__derivatives_8h_source.html", null ],
    [ "mpi_evaluation.h", "mpi__evaluation_8h.html", "mpi__evaluation_8h" ],
    [ "mpi_grid.h", "mpi__grid_8h.html", null ],
    [ "mpi_init.h", "mpi__init_8h_source.html", null ],
    [ "mpi_matrix.h", "mpi__matrix_8h_source.html", null ],
    [ "mpi_matrix_blas.h", "mpi__matrix__blas_8h_source.html", null ],
    [ "mpi_precon.h", "mpi__precon_8h_source.html", null ],
    [ "mpi_precon_blas.h", "mpi__precon__blas_8h_source.html", null ],
    [ "mpi_vector.h", "mpi__vector_8h_source.html", null ],
    [ "mpi_vector_blas.h", "mpi__vector__blas_8h_source.html", null ],
    [ "operator.h", "operator_8h_source.html", null ],
    [ "sparseblockmat.h", "sparseblockmat_8h_source.html", null ],
    [ "sparseblockmat_omp_kernels.h", "sparseblockmat__omp__kernels_8h_source.html", null ],
    [ "transpose.h", "transpose_8h_source.html", null ],
    [ "vector_categories.h", "vector__categories_8h_source.html", null ],
    [ "vector_traits.h", "vector__traits_8h_source.html", null ]
];