var hierarchy =
[
    [ "dg::AB< k, Vector >", "structdg_1_1_a_b.html", null ],
    [ "dg::ABS< T >", "structdg_1_1_a_b_s.html", null ],
    [ "dg::AbsMax< T >", "structdg_1_1_abs_max.html", null ],
    [ "dg::AbsMin< T >", "structdg_1_1_abs_min.html", null ],
    [ "dg::AnyMatrixTag", "structdg_1_1_any_matrix_tag.html", [
      [ "dg::CuspMatrixTag", "structdg_1_1_cusp_matrix_tag.html", null ],
      [ "dg::dx_matrixTag", "structdg_1_1dx__matrix_tag.html", null ],
      [ "dg::MPIMatrixTag", "structdg_1_1_m_p_i_matrix_tag.html", null ],
      [ "dg::MPIPreconTag", "structdg_1_1_m_p_i_precon_tag.html", null ],
      [ "dg::ThrustMatrixTag", "structdg_1_1_thrust_matrix_tag.html", null ]
    ] ],
    [ "dg::AnyVectorTag", "structdg_1_1_any_vector_tag.html", [
      [ "dg::MPIVectorTag", "structdg_1_1_m_p_i_vector_tag.html", null ],
      [ "dg::StdVectorTag", "structdg_1_1_std_vector_tag.html", null ],
      [ "dg::ThrustVectorTag", "structdg_1_1_thrust_vector_tag.html", null ]
    ] ],
    [ "dg::ArakawaX< Matrix, container >", "structdg_1_1_arakawa_x.html", null ],
    [ "dg::BathRZ", "structdg_1_1_bath_r_z.html", null ],
    [ "dg::BijectiveComm< Index, Vector >", "structdg_1_1_bijective_comm.html", null ],
    [ "dg::BoxIntegrator< Field, Grid >", "structdg_1_1_box_integrator.html", null ],
    [ "dg::CG< Vector >", "classdg_1_1_c_g.html", null ],
    [ "dg::CG< container >", "classdg_1_1_c_g.html", null ],
    [ "dg::ColDistMat< LocalMatrix, Collective >", "structdg_1_1_col_dist_mat.html", null ],
    [ "dg::CONSTANT", "structdg_1_1_c_o_n_s_t_a_n_t.html", null ],
    [ "dg::CooSparseBlockMat", "structdg_1_1_coo_sparse_block_mat.html", null ],
    [ "dg::CooSparseBlockMatDevice", "structdg_1_1_coo_sparse_block_mat_device.html", null ],
    [ "dg::DefaultLimiter", "structdg_1_1_default_limiter.html", null ],
    [ "dg::DifferenceNorm< container >", "structdg_1_1_difference_norm.html", null ],
    [ "dg::DLT< T >", "classdg_1_1_d_l_t.html", null ],
    [ "dg::DLT< double >", "classdg_1_1_d_l_t.html", null ],
    [ "dg::DS< FA, Matrix, container >", "structdg_1_1_d_s.html", null ],
    [ "dg::Elliptic< Matrix, Vector, Preconditioner >", "classdg_1_1_elliptic.html", null ],
    [ "dg::EllSparseBlockMat", "structdg_1_1_ell_sparse_block_mat.html", null ],
    [ "dg::EllSparseBlockMatDevice", "structdg_1_1_ell_sparse_block_mat_device.html", null ],
    [ "exception", null, [
      [ "dg::Fail", "structdg_1_1_fail.html", null ],
      [ "dg::KeineNST_1D", "classdg_1_1_keine_n_s_t__1_d.html", null ],
      [ "dg::NotANumber", "structdg_1_1_not_a_number.html", null ],
      [ "dg::Ooops", "structdg_1_1_ooops.html", null ]
    ] ],
    [ "dg::EXP< T >", "structdg_1_1_e_x_p.html", null ],
    [ "dg::ExpProfX", "structdg_1_1_exp_prof_x.html", null ],
    [ "dg::FieldAligned< Matrix, container >", "structdg_1_1_field_aligned.html", null ],
    [ "dg::FieldAligned< LocalMatrix, LocalContainer >", "structdg_1_1_field_aligned.html", null ],
    [ "dg::Gaussian", "structdg_1_1_gaussian.html", null ],
    [ "dg::Gaussian3d", "structdg_1_1_gaussian3d.html", null ],
    [ "dg::GaussianX", "structdg_1_1_gaussian_x.html", null ],
    [ "dg::GaussianY", "structdg_1_1_gaussian_y.html", null ],
    [ "dg::GaussianZ", "structdg_1_1_gaussian_z.html", null ],
    [ "dg::GeneralElliptic< Matrix, Vector, Preconditioner >", "structdg_1_1_general_elliptic.html", null ],
    [ "dg::GeneralEllipticSym< Matrix, Vector, Preconditioner >", "structdg_1_1_general_elliptic_sym.html", null ],
    [ "dg::Grid1d< T >", "structdg_1_1_grid1d.html", null ],
    [ "dg::Grid1d< double >", "structdg_1_1_grid1d.html", null ],
    [ "dg::Grid2d< T >", "structdg_1_1_grid2d.html", null ],
    [ "dg::Grid2d< double >", "structdg_1_1_grid2d.html", null ],
    [ "dg::Grid3d< T >", "structdg_1_1_grid3d.html", null ],
    [ "dg::Grid3d< double >", "structdg_1_1_grid3d.html", null ],
    [ "dg::Helmholtz< Matrix, Vector, Preconditioner >", "structdg_1_1_helmholtz.html", null ],
    [ "dg::Helmholtz2< Matrix, Vector, Preconditioner >", "structdg_1_1_helmholtz2.html", null ],
    [ "dg::Histogram< container >", "structdg_1_1_histogram.html", null ],
    [ "dg::Histogram2D< container >", "structdg_1_1_histogram2_d.html", null ],
    [ "dg::Invert< container >", "structdg_1_1_invert.html", null ],
    [ "dg::Karniadakis< Vector >", "structdg_1_1_karniadakis.html", null ],
    [ "dg::Lamb", "structdg_1_1_lamb.html", null ],
    [ "dg::LinearX", "structdg_1_1_linear_x.html", null ],
    [ "dg::LinearY", "structdg_1_1_linear_y.html", null ],
    [ "dg::LN< T >", "structdg_1_1_l_n.html", null ],
    [ "dg::MinMod< T >", "structdg_1_1_min_mod.html", null ],
    [ "dg::MOD< T >", "structdg_1_1_m_o_d.html", null ],
    [ "dg::MPI_FieldAligned< LocalMatrix, Communicator, LocalContainer >", "structdg_1_1_m_p_i___field_aligned.html", null ],
    [ "dg::MPI_Grid2d", "structdg_1_1_m_p_i___grid2d.html", null ],
    [ "dg::MPI_Grid3d", "structdg_1_1_m_p_i___grid3d.html", null ],
    [ "dg::MPI_Vector< container >", "structdg_1_1_m_p_i___vector.html", null ],
    [ "dg::MPI_Vector< LocalContainer >", "structdg_1_1_m_p_i___vector.html", null ],
    [ "dg::NearestNeighborComm< Index, Vector >", "structdg_1_1_nearest_neighbor_comm.html", null ],
    [ "dg::NoLimiter", "structdg_1_1_no_limiter.html", null ],
    [ "dg::Operator< T >", "classdg_1_1_operator.html", null ],
    [ "dg::PLUS< T >", "structdg_1_1_p_l_u_s.html", null ],
    [ "dg::Poisson< Matrix, container >", "structdg_1_1_poisson.html", null ],
    [ "dg::PoloidalAverage< container, IndexContainer >", "structdg_1_1_poloidal_average.html", null ],
    [ "dg::PoloidalAverage< MPI_Vector< container >, MPI_Vector< IndexContainer > >", "structdg_1_1_poloidal_average_3_01_m_p_i___vector_3_01container_01_4_00_01_m_p_i___vector_3_01_index_container_01_4_01_4.html", null ],
    [ "dg::POSVALUE< T >", "structdg_1_1_p_o_s_v_a_l_u_e.html", null ],
    [ "dg::RK< k, Vector >", "structdg_1_1_r_k.html", null ],
    [ "dg::rk_coeff< k >", "structdg_1_1rk__coeff.html", null ],
    [ "dg::RowColDistMat< LocalMatrixInner, LocalMatrixOuter, Collective >", "structdg_1_1_row_col_dist_mat.html", null ],
    [ "dg::RowDistMat< LocalMatrix, Collective >", "structdg_1_1_row_dist_mat.html", null ],
    [ "dg::SelfMadeMatrixTag", "structdg_1_1_self_made_matrix_tag.html", null ],
    [ "dg::SinProfX", "structdg_1_1_sin_prof_x.html", null ],
    [ "dg::SIRK< Vector >", "structdg_1_1_s_i_r_k.html", null ],
    [ "dg::SQRT< T >", "structdg_1_1_s_q_r_t.html", null ],
    [ "dg::TanhProfX", "structdg_1_1_tanh_prof_x.html", null ],
    [ "dg::Timer", "classdg_1_1_timer.html", null ],
    [ "dg::ToroidalAverage< container >", "structdg_1_1_toroidal_average.html", null ],
    [ "dg::Vortex", "structdg_1_1_vortex.html", null ]
];