var searchData=
[
  ['c',['c',['../group__geom.html#gac186e71de1e69b391e52f0ebd4bb257f',1,'solovev::GeomParameters']]],
  ['collectivepsip',['CollectivePsip',['../structsolovev_1_1_collective_psip.html',1,'solovev']]],
  ['conformalgrid2d',['ConformalGrid2d',['../structdg_1_1_conformal_grid2d.html',1,'dg']]],
  ['conformalgrid3d',['ConformalGrid3d',['../structdg_1_1_conformal_grid3d.html',1,'dg']]],
  ['conformalmpigrid2d',['ConformalMPIGrid2d',['../structdg_1_1_conformal_m_p_i_grid2d.html',1,'dg']]],
  ['conformalmpigrid3d',['ConformalMPIGrid3d',['../structdg_1_1_conformal_m_p_i_grid3d.html',1,'dg']]],
  ['conformalrefinedgrid2d',['ConformalRefinedGrid2d',['../structdg_1_1_conformal_refined_grid2d.html',1,'dg']]],
  ['conformalrefinedgrid3d',['ConformalRefinedGrid3d',['../structdg_1_1_conformal_refined_grid3d.html',1,'dg']]],
  ['curvaturekappar',['CurvatureKappaR',['../structsolovev_1_1_curvature_kappa_r.html',1,'solovev']]],
  ['curvaturekappaz',['CurvatureKappaZ',['../structsolovev_1_1_curvature_kappa_z.html',1,'solovev']]],
  ['curvaturenablabr',['CurvatureNablaBR',['../structsolovev_1_1_curvature_nabla_b_r.html',1,'solovev']]],
  ['curvaturenablabz',['CurvatureNablaBZ',['../structsolovev_1_1_curvature_nabla_b_z.html',1,'solovev']]],
  ['curvilineargrid2d',['CurvilinearGrid2d',['../structdg_1_1_curvilinear_grid2d.html',1,'dg']]],
  ['curvilineargrid3d',['CurvilinearGrid3d',['../structdg_1_1_curvilinear_grid3d.html',1,'dg']]],
  ['curvilineargridx2d',['CurvilinearGridX2d',['../structdg_1_1_curvilinear_grid_x2d.html',1,'dg']]],
  ['curvilineargridx3d',['CurvilinearGridX3d',['../structdg_1_1_curvilinear_grid_x3d.html',1,'dg']]],
  ['curvilinearmpigrid2d',['CurvilinearMPIGrid2d',['../structdg_1_1_curvilinear_m_p_i_grid2d.html',1,'dg']]],
  ['curvilinearmpigrid3d',['CurvilinearMPIGrid3d',['../structdg_1_1_curvilinear_m_p_i_grid3d.html',1,'dg']]],
  ['curvilinearrefinedgrid2d',['CurvilinearRefinedGrid2d',['../structdg_1_1_curvilinear_refined_grid2d.html',1,'dg']]],
  ['curvilinearrefinedgrid3d',['CurvilinearRefinedGrid3d',['../structdg_1_1_curvilinear_refined_grid3d.html',1,'dg']]]
];
