var dir_5b85b054eaae83068f60d9ca3773e17d =
[
    [ "adaption.h", "adaption_8h_source.html", null ],
    [ "conformal.h", "conformal_8h_source.html", null ],
    [ "curvilinear.h", "curvilinear_8h_source.html", null ],
    [ "curvilinearX.h", "curvilinear_x_8h_source.html", null ],
    [ "fields.h", "fields_8h.html", [
      [ "FieldRZYT", "structsolovev_1_1flux_1_1_field_r_z_y_t.html", "structsolovev_1_1flux_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1flux_1_1_field_r_z_y_z.html", "structsolovev_1_1flux_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1flux_1_1_field_r_z_y.html", "structsolovev_1_1flux_1_1_field_r_z_y" ],
      [ "FieldRZYRYZY", "structsolovev_1_1flux_1_1_field_r_z_y_r_y_z_y.html", "structsolovev_1_1flux_1_1_field_r_z_y_r_y_z_y" ],
      [ "FieldRZYT", "structsolovev_1_1ribeiro_1_1_field_r_z_y_t.html", "structsolovev_1_1ribeiro_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1ribeiro_1_1_field_r_z_y_z.html", "structsolovev_1_1ribeiro_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1ribeiro_1_1_field_r_z_y.html", "structsolovev_1_1ribeiro_1_1_field_r_z_y" ],
      [ "FieldRZYRYZY", "structsolovev_1_1ribeiro_1_1_field_r_z_y_r_y_z_y.html", "structsolovev_1_1ribeiro_1_1_field_r_z_y_r_y_z_y" ],
      [ "FieldRZYT", "structsolovev_1_1equalarc_1_1_field_r_z_y_t.html", "structsolovev_1_1equalarc_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1equalarc_1_1_field_r_z_y_z.html", "structsolovev_1_1equalarc_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1equalarc_1_1_field_r_z_y.html", "structsolovev_1_1equalarc_1_1_field_r_z_y" ],
      [ "FieldRZYRYZY", "structsolovev_1_1equalarc_1_1_field_r_z_y_r_y_z_y.html", "structsolovev_1_1equalarc_1_1_field_r_z_y_r_y_z_y" ]
    ] ],
    [ "flux.h", "flux_8h_source.html", null ],
    [ "guenther.h", "guenther_8h.html", null ],
    [ "guenther_parameters.h", "guenther__parameters_8h.html", null ],
    [ "hector.h", "hector_8h_source.html", null ],
    [ "hectorX.h", "hector_x_8h_source.html", null ],
    [ "init.h", "init_8h.html", null ],
    [ "mpi_conformal.h", "mpi__conformal_8h_source.html", null ],
    [ "mpi_curvilinear.h", "mpi__curvilinear_8h_source.html", null ],
    [ "mpi_orthogonal.h", "mpi__orthogonal_8h_source.html", null ],
    [ "orthogonal.h", "orthogonal_8h_source.html", null ],
    [ "orthogonalX.h", "orthogonal_x_8h_source.html", null ],
    [ "refined_conformal.h", "refined__conformal_8h_source.html", null ],
    [ "refined_curvilinear.h", "refined__curvilinear_8h_source.html", null ],
    [ "refined_orthogonal.h", "refined__orthogonal_8h_source.html", null ],
    [ "refined_orthogonalX.h", "refined__orthogonal_x_8h_source.html", null ],
    [ "ribeiro.h", "ribeiro_8h_source.html", null ],
    [ "solovev.h", "solovev_8h.html", null ],
    [ "solovev_doc.h", "solovev__doc_8h_source.html", null ],
    [ "solovev_parameters.h", "solovev__parameters_8h.html", null ],
    [ "taylor.h", "taylor_8h.html", null ],
    [ "utilities.h", "utilities_8h_source.html", null ],
    [ "utilitiesX.h", "utilities_x_8h_source.html", null ]
];