var dir_5b85b054eaae83068f60d9ca3773e17d =
[
    [ "boozer.h", "boozer_8h_source.html", null ],
    [ "conformal.h", "conformal_8h_source.html", null ],
    [ "equalarc.h", "equalarc_8h_source.html", null ],
    [ "fields.h", "fields_8h.html", [
      [ "FieldY", "structsolovev_1_1flux2_1_1_field_y.html", "structsolovev_1_1flux2_1_1_field_y" ],
      [ "FieldRZYT", "structsolovev_1_1flux2_1_1_field_r_z_y_t.html", "structsolovev_1_1flux2_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1flux2_1_1_field_r_z_y_z.html", "structsolovev_1_1flux2_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1flux2_1_1_field_r_z_y.html", "structsolovev_1_1flux2_1_1_field_r_z_y" ],
      [ "FieldRZYRYZY", "structsolovev_1_1flux2_1_1_field_r_z_y_r_y_z_y.html", "structsolovev_1_1flux2_1_1_field_r_z_y_r_y_z_y" ],
      [ "FieldY", "structsolovev_1_1flux_1_1_field_y.html", "structsolovev_1_1flux_1_1_field_y" ],
      [ "FieldRZYT", "structsolovev_1_1flux_1_1_field_r_z_y_t.html", "structsolovev_1_1flux_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1flux_1_1_field_r_z_y_z.html", "structsolovev_1_1flux_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1flux_1_1_field_r_z_y.html", "structsolovev_1_1flux_1_1_field_r_z_y" ],
      [ "FieldRZYRYZY", "structsolovev_1_1flux_1_1_field_r_z_y_r_y_z_y.html", "structsolovev_1_1flux_1_1_field_r_z_y_r_y_z_y" ],
      [ "FieldY", "structsolovev_1_1conformal_1_1_field_y.html", "structsolovev_1_1conformal_1_1_field_y" ],
      [ "FieldRZYT", "structsolovev_1_1conformal_1_1_field_r_z_y_t.html", "structsolovev_1_1conformal_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1conformal_1_1_field_r_z_y_z.html", "structsolovev_1_1conformal_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1conformal_1_1_field_r_z_y.html", "structsolovev_1_1conformal_1_1_field_r_z_y" ],
      [ "FieldRZYRYZY", "structsolovev_1_1conformal_1_1_field_r_z_y_r_y_z_y.html", "structsolovev_1_1conformal_1_1_field_r_z_y_r_y_z_y" ],
      [ "FieldY", "structsolovev_1_1equalarc_1_1_field_y.html", "structsolovev_1_1equalarc_1_1_field_y" ],
      [ "FieldRZYT", "structsolovev_1_1equalarc_1_1_field_r_z_y_t.html", "structsolovev_1_1equalarc_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1equalarc_1_1_field_r_z_y_z.html", "structsolovev_1_1equalarc_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1equalarc_1_1_field_r_z_y.html", "structsolovev_1_1equalarc_1_1_field_r_z_y" ],
      [ "FieldRZYRYZY", "structsolovev_1_1equalarc_1_1_field_r_z_y_r_y_z_y.html", "structsolovev_1_1equalarc_1_1_field_r_z_y_r_y_z_y" ],
      [ "FieldY", "structsolovev_1_1boozer_1_1_field_y.html", "structsolovev_1_1boozer_1_1_field_y" ],
      [ "FieldRZYT", "structsolovev_1_1boozer_1_1_field_r_z_y_t.html", "structsolovev_1_1boozer_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1boozer_1_1_field_r_z_y_z.html", "structsolovev_1_1boozer_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1boozer_1_1_field_r_z_y.html", "structsolovev_1_1boozer_1_1_field_r_z_y" ],
      [ "FieldRZYRYZY", "structsolovev_1_1boozer_1_1_field_r_z_y_r_y_z_y.html", "structsolovev_1_1boozer_1_1_field_r_z_y_r_y_z_y" ],
      [ "FieldY", "structsolovev_1_1hamada_1_1_field_y.html", "structsolovev_1_1hamada_1_1_field_y" ],
      [ "FieldRZYT", "structsolovev_1_1hamada_1_1_field_r_z_y_t.html", "structsolovev_1_1hamada_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1hamada_1_1_field_r_z_y_z.html", "structsolovev_1_1hamada_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1hamada_1_1_field_r_z_y.html", "structsolovev_1_1hamada_1_1_field_r_z_y" ],
      [ "FieldRZYRYZY", "structsolovev_1_1hamada_1_1_field_r_z_y_r_y_z_y.html", "structsolovev_1_1hamada_1_1_field_r_z_y_r_y_z_y" ],
      [ "FieldRZYT", "structsolovev_1_1orthogonal_1_1_field_r_z_y_t.html", "structsolovev_1_1orthogonal_1_1_field_r_z_y_t" ],
      [ "FieldRZYZ", "structsolovev_1_1orthogonal_1_1_field_r_z_y_z.html", "structsolovev_1_1orthogonal_1_1_field_r_z_y_z" ],
      [ "FieldRZY", "structsolovev_1_1orthogonal_1_1_field_r_z_y.html", "structsolovev_1_1orthogonal_1_1_field_r_z_y" ]
    ] ],
    [ "flux.h", "flux_8h_source.html", null ],
    [ "flux2.h", "flux2_8h_source.html", null ],
    [ "guenther.h", "guenther_8h.html", null ],
    [ "guenther_parameters.h", "guenther__parameters_8h.html", null ],
    [ "hamada.h", "hamada_8h_source.html", null ],
    [ "init.h", "init_8h.html", null ],
    [ "mpi_conformal.h", "mpi__conformal_8h_source.html", null ],
    [ "mpi_orthogonal.h", "mpi__orthogonal_8h_source.html", null ],
    [ "orthogonal.h", "orthogonal_8h_source.html", null ],
    [ "solovev.h", "solovev_8h.html", null ],
    [ "solovev_doc.h", "solovev__doc_8h_source.html", null ],
    [ "solovev_parameters.h", "solovev__parameters_8h.html", null ]
];