var hierarchy =
[
    [ "solovev::Alpha", "structsolovev_1_1_alpha.html", null ],
    [ "guenther::B", "structguenther_1_1_b.html", null ],
    [ "solovev::BHatP", "structsolovev_1_1_b_hat_p.html", null ],
    [ "solovev::BHatR", "structsolovev_1_1_b_hat_r.html", null ],
    [ "solovev::BHatZ", "structsolovev_1_1_b_hat_z.html", null ],
    [ "solovev::BmodTheta", "structsolovev_1_1_bmod_theta.html", null ],
    [ "solovev::Bmodule", "structsolovev_1_1_bmodule.html", null ],
    [ "solovev::BR", "structsolovev_1_1_b_r.html", null ],
    [ "guenther::bt", "structguenther_1_1bt.html", null ],
    [ "solovev::BZ", "structsolovev_1_1_b_z.html", null ],
    [ "solovev::CollectivePsip", "structsolovev_1_1_collective_psip.html", null ],
    [ "solovev::CurvatureKappaR", "structsolovev_1_1_curvature_kappa_r.html", null ],
    [ "solovev::CurvatureKappaZ", "structsolovev_1_1_curvature_kappa_z.html", null ],
    [ "solovev::CurvatureNablaBR", "structsolovev_1_1_curvature_nabla_b_r.html", null ],
    [ "solovev::CurvatureNablaBZ", "structsolovev_1_1_curvature_nabla_b_z.html", null ],
    [ "solovev::DeltaFunction", "structsolovev_1_1_delta_function.html", null ],
    [ "solovev::DeriNeu", "structsolovev_1_1_deri_neu.html", null ],
    [ "guenther::DeriNeu", "structguenther_1_1_deri_neu.html", null ],
    [ "guenther::DeriNeu2", "structguenther_1_1_deri_neu2.html", null ],
    [ "guenther::DeriNeuT", "structguenther_1_1_deri_neu_t.html", null ],
    [ "guenther::DeriNeuT2", "structguenther_1_1_deri_neu_t2.html", null ],
    [ "solovev::DeriTestFunction", "structsolovev_1_1_deri_test_function.html", null ],
    [ "guenther::Divb", "structguenther_1_1_divb.html", null ],
    [ "solovev::DivCurvatureKappa", "structsolovev_1_1_div_curvature_kappa.html", null ],
    [ "dg::DivLiseikinX< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1_div_liseikin_x.html", null ],
    [ "dg::DivLiseikinY< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1_div_liseikin_y.html", null ],
    [ "solovev::EllipticDirNeuM", "structsolovev_1_1_elliptic_dir_neu_m.html", null ],
    [ "solovev::EllipticDirPerM", "structsolovev_1_1_elliptic_dir_per_m.html", null ],
    [ "solovev::EllipticDirSimpleM", "structsolovev_1_1_elliptic_dir_simple_m.html", null ],
    [ "dg::Field", "structdg_1_1_field.html", null ],
    [ "solovev::Field", "structsolovev_1_1_field.html", null ],
    [ "guenther::Field", "structguenther_1_1_field.html", null ],
    [ "solovev::FieldP", "structsolovev_1_1_field_p.html", null ],
    [ "guenther::FieldP", "structguenther_1_1_field_p.html", null ],
    [ "solovev::FieldR", "structsolovev_1_1_field_r.html", null ],
    [ "guenther::FieldR", "structguenther_1_1_field_r.html", null ],
    [ "solovev::FieldRZtau< PsiR, PsiZ >", "structsolovev_1_1_field_r_ztau.html", null ],
    [ "solovev::FieldRZtau< PsiX, PsiY >", "structsolovev_1_1_field_r_ztau.html", null ],
    [ "solovev::flux::FieldRZY< PsiR, PsiZ, Ipol >", "structsolovev_1_1flux_1_1_field_r_z_y.html", null ],
    [ "solovev::ribeiro::FieldRZY< PsiR, PsiZ >", "structsolovev_1_1ribeiro_1_1_field_r_z_y.html", null ],
    [ "solovev::equalarc::FieldRZY< PsiR, PsiZ >", "structsolovev_1_1equalarc_1_1_field_r_z_y.html", null ],
    [ "solovev::flux::FieldRZYRYZY< PsiR, PsiZ, PsiRR, PsiRZ, PsiZZ, Ipol, IpolR, IpolZ >", "structsolovev_1_1flux_1_1_field_r_z_y_r_y_z_y.html", null ],
    [ "solovev::ribeiro::FieldRZYRYZY< PsiR, PsiZ, PsiRR, PsiRZ, PsiZZ >", "structsolovev_1_1ribeiro_1_1_field_r_z_y_r_y_z_y.html", null ],
    [ "solovev::equalarc::FieldRZYRYZY< PsiR, PsiZ, PsiRR, PsiRZ, PsiZZ >", "structsolovev_1_1equalarc_1_1_field_r_z_y_r_y_z_y.html", null ],
    [ "solovev::flux::FieldRZYT< PsiR, PsiZ, Ipol >", "structsolovev_1_1flux_1_1_field_r_z_y_t.html", null ],
    [ "solovev::ribeiro::FieldRZYT< PsiR, PsiZ >", "structsolovev_1_1ribeiro_1_1_field_r_z_y_t.html", null ],
    [ "solovev::equalarc::FieldRZYT< PsiR, PsiZ >", "structsolovev_1_1equalarc_1_1_field_r_z_y_t.html", null ],
    [ "solovev::flux::FieldRZYT< PsiX, PsiY, Ipol >", "structsolovev_1_1flux_1_1_field_r_z_y_t.html", null ],
    [ "solovev::flux::FieldRZYZ< PsiR, PsiZ, Ipol >", "structsolovev_1_1flux_1_1_field_r_z_y_z.html", null ],
    [ "solovev::ribeiro::FieldRZYZ< PsiR, PsiZ >", "structsolovev_1_1ribeiro_1_1_field_r_z_y_z.html", null ],
    [ "solovev::equalarc::FieldRZYZ< PsiR, PsiZ >", "structsolovev_1_1equalarc_1_1_field_r_z_y_z.html", null ],
    [ "solovev::FieldT", "structsolovev_1_1_field_t.html", null ],
    [ "solovev::FieldZ", "structsolovev_1_1_field_z.html", null ],
    [ "guenther::FieldZ", "structguenther_1_1_field_z.html", null ],
    [ "dg::FluxGenerator< Psi, PsiX, PsiY, PsiXX, PsiXY, PsiYY, Ipol, IpolR, IpolZ >", "structdg_1_1_flux_generator.html", null ],
    [ "solovev::FluxSurfaceAverage< container >", "structsolovev_1_1_flux_surface_average.html", null ],
    [ "dg::flux::detail::Fpsi< Psi, PsiX, PsiY, Ipol >", "structdg_1_1flux_1_1detail_1_1_fpsi.html", null ],
    [ "solovev::FuncDirNeu", "structsolovev_1_1_func_dir_neu.html", null ],
    [ "solovev::FuncDirPer", "structsolovev_1_1_func_dir_per.html", null ],
    [ "guenther::FuncMinusDeriNeuT2", "structguenther_1_1_func_minus_deri_neu_t2.html", null ],
    [ "solovev::FuncNeu", "structsolovev_1_1_func_neu.html", null ],
    [ "guenther::FuncNeu", "structguenther_1_1_func_neu.html", null ],
    [ "guenther::FuncNeu2", "structguenther_1_1_func_neu2.html", null ],
    [ "solovev::GaussianDamping", "structsolovev_1_1_gaussian_damping.html", null ],
    [ "solovev::GaussianProfDamping", "structsolovev_1_1_gaussian_prof_damping.html", null ],
    [ "solovev::GaussianProfXDamping", "structsolovev_1_1_gaussian_prof_x_damping.html", null ],
    [ "solovev::GeomParameters", "structsolovev_1_1_geom_parameters.html", null ],
    [ "solovev::GradLnB", "structsolovev_1_1_grad_ln_b.html", null ],
    [ "guenther::GradLnB", "structguenther_1_1_grad_ln_b.html", null ],
    [ "dg::Grid2d", "../../../inc/dg/html/structdg_1_1_grid2d.html", [
      [ "dg::ConformalGrid2d< container >", "structdg_1_1_conformal_grid2d.html", null ],
      [ "dg::CurvilinearGrid2d< container >", "structdg_1_1_curvilinear_grid2d.html", null ],
      [ "dg::OrthogonalGrid2d< container >", "structdg_1_1_orthogonal_grid2d.html", null ],
      [ "dg::RefinedGrid2d", "../../../inc/dg/html/structdg_1_1_refined_grid2d.html", [
        [ "dg::ConformalRefinedGrid2d< container >", "structdg_1_1_conformal_refined_grid2d.html", null ],
        [ "dg::CurvilinearRefinedGrid2d< container >", "structdg_1_1_curvilinear_refined_grid2d.html", null ],
        [ "dg::OrthogonalRefinedGrid2d< container >", "structdg_1_1_orthogonal_refined_grid2d.html", null ]
      ] ]
    ] ],
    [ "dg::Grid3d", "../../../inc/dg/html/structdg_1_1_grid3d.html", [
      [ "dg::ConformalGrid3d< container >", "structdg_1_1_conformal_grid3d.html", null ],
      [ "dg::CurvilinearGrid3d< container >", "structdg_1_1_curvilinear_grid3d.html", null ],
      [ "dg::OrthogonalGrid3d< container >", "structdg_1_1_orthogonal_grid3d.html", null ],
      [ "dg::RefinedGrid3d", "../../../inc/dg/html/structdg_1_1_refined_grid3d.html", [
        [ "dg::ConformalRefinedGrid3d< container >", "structdg_1_1_conformal_refined_grid3d.html", null ],
        [ "dg::CurvilinearRefinedGrid3d< container >", "structdg_1_1_curvilinear_refined_grid3d.html", null ],
        [ "dg::OrthogonalRefinedGrid3d< container >", "structdg_1_1_orthogonal_refined_grid3d.html", null ]
      ] ]
    ] ],
    [ "dg::GridX2d", "../../../inc/dg/html/structdg_1_1_grid_x2d.html", [
      [ "dg::CurvilinearGridX2d< container >", "structdg_1_1_curvilinear_grid_x2d.html", null ],
      [ "dg::OrthogonalGridX2d< container >", "structdg_1_1_orthogonal_grid_x2d.html", null ],
      [ "dg::RefinedGridX2d", "../../../inc/dg/html/structdg_1_1_refined_grid_x2d.html", [
        [ "dg::OrthogonalRefinedGridX2d< container >", "structdg_1_1_orthogonal_refined_grid_x2d.html", null ]
      ] ]
    ] ],
    [ "dg::GridX3d", "../../../inc/dg/html/structdg_1_1_grid_x3d.html", [
      [ "dg::CurvilinearGridX3d< container >", "structdg_1_1_curvilinear_grid_x3d.html", null ],
      [ "dg::OrthogonalGridX3d< container >", "structdg_1_1_orthogonal_grid_x3d.html", null ],
      [ "dg::RefinedGridX3d", "../../../inc/dg/html/structdg_1_1_refined_grid_x3d.html", [
        [ "dg::OrthogonalRefinedGridX3d< container >", "structdg_1_1_orthogonal_refined_grid_x3d.html", null ]
      ] ]
    ] ],
    [ "dg::Hector< IMatrix, Matrix, container >", "structdg_1_1_hector.html", null ],
    [ "dg::HectorX< IMatrix, Matrix, container >", "structdg_1_1_hector_x.html", null ],
    [ "solovev::HessianRZtau< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structsolovev_1_1_hessian_r_ztau.html", null ],
    [ "solovev::InvB", "structsolovev_1_1_inv_b.html", null ],
    [ "guenther::InvB", "structguenther_1_1_inv_b.html", null ],
    [ "taylor::Ipol", "structtaylor_1_1_ipol.html", null ],
    [ "solovev::Ipol", "structsolovev_1_1_ipol.html", null ],
    [ "taylor::IpolR", "structtaylor_1_1_ipol_r.html", null ],
    [ "solovev::IpolR", "structsolovev_1_1_ipol_r.html", null ],
    [ "taylor::IpolZ", "structtaylor_1_1_ipol_z.html", null ],
    [ "solovev::IpolZ", "structsolovev_1_1_ipol_z.html", null ],
    [ "solovev::Iris", "structsolovev_1_1_iris.html", null ],
    [ "dg::detail::LaplaceAdaptPsi< PsiX, PsiY, LaplacePsi, Chi, ChiX, ChiY >", "structdg_1_1detail_1_1_laplace_adapt_psi.html", null ],
    [ "dg::detail::LaplaceChiPsi< PsiX, PsiY, PsiXX, PsiXY, PsiYY, ChiXX, ChiXY, ChiYY, DivChiX, DivChiY >", "structdg_1_1detail_1_1_laplace_chi_psi.html", null ],
    [ "dg::detail::LaplacePsi< PsiXX, PsiYY >", "structdg_1_1detail_1_1_laplace_psi.html", null ],
    [ "solovev::LaplacePsip", "structsolovev_1_1_laplace_psip.html", null ],
    [ "solovev::mod::LaplacePsip", "structsolovev_1_1mod_1_1_laplace_psip.html", null ],
    [ "taylor::LaplacePsip", "structtaylor_1_1_laplace_psip.html", null ],
    [ "dg::Liseikin_XX< PsiX, PsiY >", "structdg_1_1_liseikin___x_x.html", null ],
    [ "dg::Liseikin_XY< PsiX, PsiY >", "structdg_1_1_liseikin___x_y.html", null ],
    [ "dg::Liseikin_YY< PsiX, PsiY >", "structdg_1_1_liseikin___y_y.html", null ],
    [ "dg::LiseikinCollective< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1_liseikin_collective.html", null ],
    [ "solovev::LnB", "structsolovev_1_1_ln_b.html", null ],
    [ "guenther::LnB", "structguenther_1_1_ln_b.html", null ],
    [ "solovev::MinimalCurve< Psi, PsiX, PsiY >", "structsolovev_1_1_minimal_curve.html", null ],
    [ "dg::MPIGrid2d", "../../../inc/dg/html/structdg_1_1_m_p_i_grid2d.html", [
      [ "dg::ConformalMPIGrid2d< LocalContainer >", "structdg_1_1_conformal_m_p_i_grid2d.html", null ],
      [ "dg::CurvilinearMPIGrid2d< LocalContainer >", "structdg_1_1_curvilinear_m_p_i_grid2d.html", null ],
      [ "dg::OrthogonalMPIGrid2d< LocalContainer >", "structdg_1_1_orthogonal_m_p_i_grid2d.html", null ]
    ] ],
    [ "dg::MPIGrid3d", "../../../inc/dg/html/structdg_1_1_m_p_i_grid3d.html", [
      [ "dg::ConformalMPIGrid3d< LocalContainer >", "structdg_1_1_conformal_m_p_i_grid3d.html", null ],
      [ "dg::CurvilinearMPIGrid3d< LocalContainer >", "structdg_1_1_curvilinear_m_p_i_grid3d.html", null ],
      [ "dg::OrthogonalMPIGrid3d< LocalContainer >", "structdg_1_1_orthogonal_m_p_i_grid3d.html", null ]
    ] ],
    [ "dg::NablaPsiInv< PsiX, PsiY >", "structdg_1_1_nabla_psi_inv.html", null ],
    [ "dg::NablaPsiInvCollective< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1_nabla_psi_inv_collective.html", null ],
    [ "dg::NablaPsiInvX< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1_nabla_psi_inv_x.html", null ],
    [ "dg::NablaPsiInvY< PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1_nabla_psi_inv_y.html", null ],
    [ "solovev::Nprofile", "structsolovev_1_1_nprofile.html", null ],
    [ "solovev::PsiLimiter", "structsolovev_1_1_psi_limiter.html", null ],
    [ "taylor::Psip", "structtaylor_1_1_psip.html", null ],
    [ "solovev::mod::Psip", "structsolovev_1_1mod_1_1_psip.html", null ],
    [ "solovev::Psip", "structsolovev_1_1_psip.html", null ],
    [ "solovev::PsipR", "structsolovev_1_1_psip_r.html", null ],
    [ "taylor::PsipR", "structtaylor_1_1_psip_r.html", null ],
    [ "solovev::mod::PsipR", "structsolovev_1_1mod_1_1_psip_r.html", null ],
    [ "solovev::mod::PsipRR", "structsolovev_1_1mod_1_1_psip_r_r.html", null ],
    [ "taylor::PsipRR", "structtaylor_1_1_psip_r_r.html", null ],
    [ "solovev::PsipRR", "structsolovev_1_1_psip_r_r.html", null ],
    [ "taylor::PsipRZ", "structtaylor_1_1_psip_r_z.html", null ],
    [ "solovev::mod::PsipRZ", "structsolovev_1_1mod_1_1_psip_r_z.html", null ],
    [ "solovev::PsipRZ", "structsolovev_1_1_psip_r_z.html", null ],
    [ "solovev::PsiPupil", "structsolovev_1_1_psi_pupil.html", null ],
    [ "solovev::mod::PsipZ", "structsolovev_1_1mod_1_1_psip_z.html", null ],
    [ "solovev::PsipZ", "structsolovev_1_1_psip_z.html", null ],
    [ "taylor::PsipZ", "structtaylor_1_1_psip_z.html", null ],
    [ "solovev::mod::PsipZZ", "structsolovev_1_1mod_1_1_psip_z_z.html", null ],
    [ "taylor::PsipZZ", "structtaylor_1_1_psip_z_z.html", null ],
    [ "solovev::PsipZZ", "structsolovev_1_1_psip_z_z.html", null ],
    [ "solovev::Pupil", "structsolovev_1_1_pupil.html", null ],
    [ "dg::Ribeiro< Psi, PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1_ribeiro.html", null ],
    [ "dg::RibeiroFluxGenerator< Psi, PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1_ribeiro_flux_generator.html", null ],
    [ "dg::RibeiroX< Psi, PsiX, PsiY, PsiXX, PsiXY, PsiYY >", "structdg_1_1_ribeiro_x.html", null ],
    [ "solovev::SafetyFactor< container >", "structsolovev_1_1_safety_factor.html", null ],
    [ "dg::SeparatrixOrthogonal< Psi, PsiX, PsiY, LaplacePsi >", "structdg_1_1_separatrix_orthogonal.html", null ],
    [ "dg::SimpleOrthogonal< Psi, PsiX, PsiY, LaplacePsi >", "structdg_1_1_simple_orthogonal.html", null ],
    [ "dg::SimpleOrthogonalX< Psi, PsiX, PsiY, LaplacePsi >", "structdg_1_1_simple_orthogonal_x.html", null ],
    [ "solovev::TanhSource", "structsolovev_1_1_tanh_source.html", null ],
    [ "solovev::TestFunction", "structsolovev_1_1_test_function.html", null ],
    [ "solovev::ZonalFlow", "structsolovev_1_1_zonal_flow.html", null ]
];