var hierarchy =
[
    [ "solovev::Alpha", "structsolovev_1_1_alpha.html", null ],
    [ "guenther::B", "structguenther_1_1_b.html", null ],
    [ "solovev::BHatP", "structsolovev_1_1_b_hat_p.html", null ],
    [ "solovev::BHatR", "structsolovev_1_1_b_hat_r.html", null ],
    [ "solovev::BHatZ", "structsolovev_1_1_b_hat_z.html", null ],
    [ "solovev::BmodTheta", "structsolovev_1_1_bmod_theta.html", null ],
    [ "solovev::Bmodule", "structsolovev_1_1_bmodule.html", null ],
    [ "solovev::BR", "structsolovev_1_1_b_r.html", null ],
    [ "guenther::bt", "structguenther_1_1bt.html", null ],
    [ "solovev::BZ", "structsolovev_1_1_b_z.html", null ],
    [ "solovev::CurvatureR", "structsolovev_1_1_curvature_r.html", null ],
    [ "solovev::CurvatureZ", "structsolovev_1_1_curvature_z.html", null ],
    [ "solovev::DeltaFunction", "structsolovev_1_1_delta_function.html", null ],
    [ "solovev::DeriNeu", "structsolovev_1_1_deri_neu.html", null ],
    [ "guenther::DeriNeu", "structguenther_1_1_deri_neu.html", null ],
    [ "guenther::DeriNeu2", "structguenther_1_1_deri_neu2.html", null ],
    [ "guenther::DeriNeuT", "structguenther_1_1_deri_neu_t.html", null ],
    [ "guenther::DeriNeuT2", "structguenther_1_1_deri_neu_t2.html", null ],
    [ "solovev::DeriTestFunction", "structsolovev_1_1_deri_test_function.html", null ],
    [ "guenther::Divb", "structguenther_1_1_divb.html", null ],
    [ "solovev::EllipticDirNeuM", "structsolovev_1_1_elliptic_dir_neu_m.html", null ],
    [ "solovev::EllipticDirPerM", "structsolovev_1_1_elliptic_dir_per_m.html", null ],
    [ "boozer::Field", "structboozer_1_1_field.html", null ],
    [ "orthogonal::Field", "structorthogonal_1_1_field.html", null ],
    [ "conformal::Field", "structconformal_1_1_field.html", null ],
    [ "flux::Field", "structflux_1_1_field.html", null ],
    [ "flux2::Field", "structflux2_1_1_field.html", null ],
    [ "solovev::Field", "structsolovev_1_1_field.html", null ],
    [ "equalarc::Field", "structequalarc_1_1_field.html", null ],
    [ "guenther::Field", "structguenther_1_1_field.html", null ],
    [ "hamada::Field", "structhamada_1_1_field.html", null ],
    [ "orthogonal::detail::FieldFinv", "structorthogonal_1_1detail_1_1_field_finv.html", null ],
    [ "flux::detail::FieldFinv", "structflux_1_1detail_1_1_field_finv.html", null ],
    [ "boozer::detail::FieldFinv", "structboozer_1_1detail_1_1_field_finv.html", null ],
    [ "flux2::detail::FieldFinv", "structflux2_1_1detail_1_1_field_finv.html", null ],
    [ "equalarc::detail::FieldFinv", "structequalarc_1_1detail_1_1_field_finv.html", null ],
    [ "conformal::detail::FieldFinv", "structconformal_1_1detail_1_1_field_finv.html", null ],
    [ "hamada::detail::FieldFinv", "structhamada_1_1detail_1_1_field_finv.html", null ],
    [ "solovev::FieldP", "structsolovev_1_1_field_p.html", null ],
    [ "guenther::FieldP", "structguenther_1_1_field_p.html", null ],
    [ "guenther::FieldR", "structguenther_1_1_field_r.html", null ],
    [ "solovev::FieldR", "structsolovev_1_1_field_r.html", null ],
    [ "solovev::FieldRZ", "structsolovev_1_1_field_r_z.html", null ],
    [ "solovev::FieldRZtau", "structsolovev_1_1_field_r_ztau.html", null ],
    [ "solovev::flux2::FieldRZY", "structsolovev_1_1flux2_1_1_field_r_z_y.html", null ],
    [ "solovev::flux::FieldRZY", "structsolovev_1_1flux_1_1_field_r_z_y.html", null ],
    [ "solovev::conformal::FieldRZY", "structsolovev_1_1conformal_1_1_field_r_z_y.html", null ],
    [ "solovev::equalarc::FieldRZY", "structsolovev_1_1equalarc_1_1_field_r_z_y.html", null ],
    [ "solovev::boozer::FieldRZY", "structsolovev_1_1boozer_1_1_field_r_z_y.html", null ],
    [ "solovev::hamada::FieldRZY", "structsolovev_1_1hamada_1_1_field_r_z_y.html", null ],
    [ "solovev::orthogonal::FieldRZY", "structsolovev_1_1orthogonal_1_1_field_r_z_y.html", null ],
    [ "solovev::flux2::FieldRZYRYZY", "structsolovev_1_1flux2_1_1_field_r_z_y_r_y_z_y.html", null ],
    [ "solovev::flux::FieldRZYRYZY", "structsolovev_1_1flux_1_1_field_r_z_y_r_y_z_y.html", null ],
    [ "solovev::conformal::FieldRZYRYZY", "structsolovev_1_1conformal_1_1_field_r_z_y_r_y_z_y.html", null ],
    [ "solovev::equalarc::FieldRZYRYZY", "structsolovev_1_1equalarc_1_1_field_r_z_y_r_y_z_y.html", null ],
    [ "solovev::boozer::FieldRZYRYZY", "structsolovev_1_1boozer_1_1_field_r_z_y_r_y_z_y.html", null ],
    [ "solovev::hamada::FieldRZYRYZY", "structsolovev_1_1hamada_1_1_field_r_z_y_r_y_z_y.html", null ],
    [ "solovev::flux::FieldRZYT", "structsolovev_1_1flux_1_1_field_r_z_y_t.html", null ],
    [ "solovev::conformal::FieldRZYT", "structsolovev_1_1conformal_1_1_field_r_z_y_t.html", null ],
    [ "solovev::equalarc::FieldRZYT", "structsolovev_1_1equalarc_1_1_field_r_z_y_t.html", null ],
    [ "solovev::boozer::FieldRZYT", "structsolovev_1_1boozer_1_1_field_r_z_y_t.html", null ],
    [ "solovev::hamada::FieldRZYT", "structsolovev_1_1hamada_1_1_field_r_z_y_t.html", null ],
    [ "solovev::orthogonal::FieldRZYT", "structsolovev_1_1orthogonal_1_1_field_r_z_y_t.html", null ],
    [ "solovev::flux2::FieldRZYT", "structsolovev_1_1flux2_1_1_field_r_z_y_t.html", null ],
    [ "solovev::flux::FieldRZYZ", "structsolovev_1_1flux_1_1_field_r_z_y_z.html", null ],
    [ "solovev::conformal::FieldRZYZ", "structsolovev_1_1conformal_1_1_field_r_z_y_z.html", null ],
    [ "solovev::equalarc::FieldRZYZ", "structsolovev_1_1equalarc_1_1_field_r_z_y_z.html", null ],
    [ "solovev::boozer::FieldRZYZ", "structsolovev_1_1boozer_1_1_field_r_z_y_z.html", null ],
    [ "solovev::hamada::FieldRZYZ", "structsolovev_1_1hamada_1_1_field_r_z_y_z.html", null ],
    [ "solovev::orthogonal::FieldRZYZ", "structsolovev_1_1orthogonal_1_1_field_r_z_y_z.html", null ],
    [ "solovev::flux2::FieldRZYZ", "structsolovev_1_1flux2_1_1_field_r_z_y_z.html", null ],
    [ "solovev::FieldT", "structsolovev_1_1_field_t.html", null ],
    [ "solovev::conformal::FieldY", "structsolovev_1_1conformal_1_1_field_y.html", null ],
    [ "solovev::equalarc::FieldY", "structsolovev_1_1equalarc_1_1_field_y.html", null ],
    [ "solovev::boozer::FieldY", "structsolovev_1_1boozer_1_1_field_y.html", null ],
    [ "solovev::flux::FieldY", "structsolovev_1_1flux_1_1_field_y.html", null ],
    [ "solovev::hamada::FieldY", "structsolovev_1_1hamada_1_1_field_y.html", null ],
    [ "solovev::flux2::FieldY", "structsolovev_1_1flux2_1_1_field_y.html", null ],
    [ "guenther::FieldZ", "structguenther_1_1_field_z.html", null ],
    [ "solovev::FieldZ", "structsolovev_1_1_field_z.html", null ],
    [ "solovev::FieldZR", "structsolovev_1_1_field_z_r.html", null ],
    [ "solovev::FluxSurfaceAverage< container >", "structsolovev_1_1_flux_surface_average.html", null ],
    [ "orthogonal::detail::Fpsi", "structorthogonal_1_1detail_1_1_fpsi.html", null ],
    [ "boozer::detail::Fpsi", "structboozer_1_1detail_1_1_fpsi.html", null ],
    [ "flux::detail::Fpsi", "structflux_1_1detail_1_1_fpsi.html", null ],
    [ "flux2::detail::Fpsi", "structflux2_1_1detail_1_1_fpsi.html", null ],
    [ "equalarc::detail::Fpsi", "structequalarc_1_1detail_1_1_fpsi.html", null ],
    [ "hamada::detail::Fpsi", "structhamada_1_1detail_1_1_fpsi.html", null ],
    [ "conformal::detail::Fpsi", "structconformal_1_1detail_1_1_fpsi.html", null ],
    [ "solovev::FuncDirNeu", "structsolovev_1_1_func_dir_neu.html", null ],
    [ "solovev::FuncDirPer", "structsolovev_1_1_func_dir_per.html", null ],
    [ "guenther::FuncMinusDeriNeuT2", "structguenther_1_1_func_minus_deri_neu_t2.html", null ],
    [ "solovev::FuncNeu", "structsolovev_1_1_func_neu.html", null ],
    [ "guenther::FuncNeu", "structguenther_1_1_func_neu.html", null ],
    [ "guenther::FuncNeu2", "structguenther_1_1_func_neu2.html", null ],
    [ "solovev::GaussianDamping", "structsolovev_1_1_gaussian_damping.html", null ],
    [ "solovev::GaussianProfDamping", "structsolovev_1_1_gaussian_prof_damping.html", null ],
    [ "solovev::GaussianProfXDamping", "structsolovev_1_1_gaussian_prof_x_damping.html", null ],
    [ "solovev::GeomParameters", "structsolovev_1_1_geom_parameters.html", null ],
    [ "guenther::GradLnB", "structguenther_1_1_grad_ln_b.html", null ],
    [ "solovev::GradLnB", "structsolovev_1_1_grad_ln_b.html", null ],
    [ "Grid2d", null, [
      [ "boozer::RingGrid2d< container >", "structboozer_1_1_ring_grid2d.html", null ],
      [ "conformal::RingGrid2d< container >", "structconformal_1_1_ring_grid2d.html", null ],
      [ "equalarc::RingGrid2d< container >", "structequalarc_1_1_ring_grid2d.html", null ],
      [ "flux2::RingGrid2d< container >", "structflux2_1_1_ring_grid2d.html", null ],
      [ "flux::RingGrid2d< container >", "structflux_1_1_ring_grid2d.html", null ],
      [ "hamada::RingGrid2d< container >", "structhamada_1_1_ring_grid2d.html", null ],
      [ "orthogonal::RingGrid2d< container >", "structorthogonal_1_1_ring_grid2d.html", null ]
    ] ],
    [ "Grid3d", null, [
      [ "boozer::RingGrid3d< container >", "structboozer_1_1_ring_grid3d.html", null ],
      [ "conformal::RingGrid3d< container >", "structconformal_1_1_ring_grid3d.html", null ],
      [ "equalarc::RingGrid3d< container >", "structequalarc_1_1_ring_grid3d.html", null ],
      [ "flux2::RingGrid3d< container >", "structflux2_1_1_ring_grid3d.html", null ],
      [ "flux::RingGrid3d< container >", "structflux_1_1_ring_grid3d.html", null ],
      [ "hamada::RingGrid3d< container >", "structhamada_1_1_ring_grid3d.html", null ],
      [ "orthogonal::RingGrid3d< container >", "structorthogonal_1_1_ring_grid3d.html", null ]
    ] ],
    [ "solovev::HessianRZtau", "structsolovev_1_1_hessian_r_ztau.html", null ],
    [ "solovev::InvB", "structsolovev_1_1_inv_b.html", null ],
    [ "guenther::InvB", "structguenther_1_1_inv_b.html", null ],
    [ "solovev::Ipol", "structsolovev_1_1_ipol.html", null ],
    [ "solovev::IpolR", "structsolovev_1_1_ipol_r.html", null ],
    [ "solovev::IpolZ", "structsolovev_1_1_ipol_z.html", null ],
    [ "solovev::Iris", "structsolovev_1_1_iris.html", null ],
    [ "solovev::LnB", "structsolovev_1_1_ln_b.html", null ],
    [ "guenther::LnB", "structguenther_1_1_ln_b.html", null ],
    [ "solovev::MinimalCurve", "structsolovev_1_1_minimal_curve.html", null ],
    [ "MPI_Grid2d", null, [
      [ "conformal::MPIRingGrid2d< LocalContainer >", "structconformal_1_1_m_p_i_ring_grid2d.html", null ],
      [ "orthogonal::MPIRingGrid2d< LocalContainer >", "structorthogonal_1_1_m_p_i_ring_grid2d.html", null ]
    ] ],
    [ "MPI_Grid3d", null, [
      [ "conformal::MPIRingGrid3d< LocalContainer >", "structconformal_1_1_m_p_i_ring_grid3d.html", null ],
      [ "orthogonal::MPIRingGrid3d< LocalContainer >", "structorthogonal_1_1_m_p_i_ring_grid3d.html", null ]
    ] ],
    [ "solovev::Nprofile", "structsolovev_1_1_nprofile.html", null ],
    [ "solovev::PsiLimiter", "structsolovev_1_1_psi_limiter.html", null ],
    [ "solovev::Psip", "structsolovev_1_1_psip.html", null ],
    [ "solovev::PsipR", "structsolovev_1_1_psip_r.html", null ],
    [ "solovev::PsipRR", "structsolovev_1_1_psip_r_r.html", null ],
    [ "solovev::PsipRZ", "structsolovev_1_1_psip_r_z.html", null ],
    [ "solovev::PsiPupil", "structsolovev_1_1_psi_pupil.html", null ],
    [ "solovev::PsipZ", "structsolovev_1_1_psip_z.html", null ],
    [ "solovev::PsipZZ", "structsolovev_1_1_psip_z_z.html", null ],
    [ "solovev::Pupil", "structsolovev_1_1_pupil.html", null ],
    [ "solovev::SafetyFactor< container >", "structsolovev_1_1_safety_factor.html", null ],
    [ "solovev::TanhSource", "structsolovev_1_1_tanh_source.html", null ],
    [ "solovev::TestFunction", "structsolovev_1_1_test_function.html", null ],
    [ "solovev::ZonalFlow", "structsolovev_1_1_zonal_flow.html", null ]
];